### Keycloak Direct Access Token 요청
POST http://localhost:8089/realms/polio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=polio-toy-client&
client_secret=I6uiQiYIegQVvvIsAgFUpexpgNjfR86H&
username=test&
password=test


> {%
    const res = response.body;
    client.global.set("user_access_token", res.access_token);
    client.global.set("user_refresh_token", res.refresh_token);
%}



### 로그아웃 - refresh_token 사용
POST http://localhost:8089/realms/polio/protocol/openid-connect/logout
Content-Type: application/x-www-form-urlencoded

client_id=polio-toy-client&
client_secret=I6uiQiYIegQVvvIsAgFUpexpgNjfR86H&
refresh_token={{user_refresh_token}}

> {%
    client.global.clear("user_access_token");
    client.global.clear("user_refresh_token");
%}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "polio-toy-client-user1",
  "password": "polio-toy-client-user1"
}

### 3. 사용자 비밀번호 변경
# 위에서 얻은 사용자 ID (userId)를 아래 URL에 넣어주세요
PUT http://localhost:8089/admin/realms/polio/users/5647cdfb-e870-4e7c-803b-47a581381558/reset-password
Content-Type: application/json
Authorization: Bearer {{client_access_token}}

{
  "type": "password",
  "value": "NEW_PASSWORD_HERE",
  "temporary": false
}


###
PUT http://localhost:8080/auth/password
Content-Type: application/json
Authorization: Bearer {{user_access_token}}

{"userId":"9d833fc5-cc1e-4b60-8f5e-27fdb3c3db70","newPassword":"test1234"}
