### Keycloak Direct Access Token 요청
POST http://localhost:8089/realms/polio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=polio-toy-client&
client_secret=I6uiQiYIegQVvvIsAgFUpexpgNjfR86H&
username=polio-toy-client-user1&
password=polio-toy-client-user1


> {%
    const res = response.body;
    client.global.set("user_access_token", res.access_token);
    client.global.set("user_refresh_token", res.refresh_token);
%}



### 로그아웃 - refresh_token 사용
POST http://localhost:8089/realms/polio/protocol/openid-connect/logout
Content-Type: application/x-www-form-urlencoded

client_id=polio-toy-client&
client_secret=I6uiQiYIegQVvvIsAgFUpexpgNjfR86H&
refresh_token={{user_refresh_token}}

> {%
    client.global.clear("user_access_token");
    client.global.clear("user_refresh_token");
%}


###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "polio-toy-client-user1",
  "password": "polio-toy-client-user1"
}



