spring:
  application:
    name: polio
  datasource:
    url: jdbc:mysql://localhost:3306/polio?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: polio
    password: polio
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000       # 10분
      connection-timeout: 30000  # 30초
      max-lifetime: 1800000      # 30분
  jpa:
    hibernate:
      ddl-auto: update

debug: true